BUG: Fix T-DaTing labels when continuing tracking
pySTEPS/pysteps pull request #280
Opened 2022-04-22 16:11 UTC by ritvje

Hi! We came across this bug when trying to use the tracking functions. When continuing the tracking from previously tracked list, the tracks were weird, for example when tracking 3 x 20-minute intervals:

![Track](https://user-images.githubusercontent.com/11709270/164752692-bf896a42-ccb3-4f37-8f06-59ca63f5b239.png)

This is because when setting the unique IDs for the tracks, the IDs of the previous cells are not considered. This PR fixes that. Here are the tracks with this fix:

![Track_fixed](https://user-images.githubusercontent.com/11709270/164752878-de16e629-ea04-42b0-9494-eeb64c019fa9.png)

2022-04-22 16:17 UTC, dnerini commented
Very good, thanks a lot @ritvje for the contribution!

@feldmann-m do you want to have a look at this PR?

2022-04-24 08:56 UTC, dnerini reviewed
The fix makes sense! Before merging, I wonder if we can also add a simple test that would have detected the bug in the first place? 

We already have a simple test in `pysteps/tests/test_tracking_tdating.py`, would you like to give it a try @ritvje ? Once done, I suggest that you try running the test without your fix to make sure that the test fails...

2022-04-24 18:35 UTC, ritvje commented
Sure, I can try to write the test! There are some clear indicators of the bug in my data, like that the track list is shorter at the second time interval than first and some tracks are not continuous in time, but I'll have to see if those repeat in the test data.

2022-04-26 17:46 UTC, ritvje commented
I now added a test. I tried to test that the logic in the result tracks is correct. However, even without the fix it won't fail for all datasets (for example,  the first timesteps of FMI test data), most likely if there are no unmatched cells in the second interval. Which makes sense, since the bug in setting the ID only affects unmatched cells. But it should fail for this configuration without the fix and pass with it.

Also, when I tried to run the tests with `tox` (as instructed in the [developer guide](https://pysteps.readthedocs.io/en/stable/developer_guide/test_pysteps.html)), it seems that the test (and also the other tdating test) is skipped because skimage is not installed in the environment. Is this fine or should I add skimage there somehow?

2022-04-27 19:55 UTC, dnerini requested changes
Very nice @ritvje , thanks a lot for adding the test! 
I guess it's fine to run it only with a single dataset that fits this particular case, so I'm happy with your current version, I only included a very minor suggestion.

Maybe let's give some more time to @feldmann-m to have a look into this PR (since she's the original author of the method) before merging into master.

Concerning tox, it's a good point, I'll think about it, but let's not address it in this PR. Thanks for pointing it out!

2022-04-27 19:55 UTC, dnerini commented on pysteps/tests/test_tracking_tdating.py
> +    input, metadata = get_precipitation_fields(
better to avoid redefining built-in method 'input', can your rename with something else, e.g. "input_fields" ?

2022-05-10 08:06 UTC, dnerini approved these changes

2022-06-09 13:28 UTC, feldmann-m commented
Thank you @ritvje for raising this issue! The fix looks great to me, this should enable the tracking module to continue tracking from existing lists.

2022-06-09 13:29 UTC, feldmann-m approved these changes

2022-06-09 13:38 UTC, merged