Nowcast refactoring master
pySTEPS/pysteps pull request #291
Opened 2022-07-16 16:00 UTC by pulkkins

This pull request contains major refactoring and polishing of the nowcasts module.

**Refactoring**
- Implement a generic utility function (nowcasts.utils.nowcast_main_loop) for iterative computation of nowcasts. The function supports adding perturbations and using parallelization, callback function or non-integer time steps.
- Rewrite the nowcasting methods using the above function to reduce the amount of redundant code.
- S-PROG and STEPS: use a common utility function for computing the wet area ratio mask to reduce redundant code.
- LINDA: implement support for non-integer time steps and the callback and return_output options as in STEPS.
- Add callback function tests for LINDA.

**Minor fixes**
- Use f-strings instead of old-style printing.
- Use consistent PEP 8-compatible naming for the inputs of the nowcasting methods (e.g. precip and velocity instead of R and V).
- Other variable name changes to enhance PEP 8-compatibility.
- Ensemble nowcasts: make sure that dask is used only when ensemble size is greater than one and do not try to allocate more workers than ensemble members.
- Fix typos and polish docstrings.
- Use consistent docstring indentation (4 spaces).

2022-07-20 11:23 UTC, RubenImhoff requested changes
Great work, Seppo! 

I have made some suggestions for the variable names, but we can let that decision depend on what the others think. 

Should we add some utils.py tests for the added utilities in nowcasts/utils.py?

2022-07-20 11:23 UTC, RubenImhoff commented on pysteps/nowcasts/__init__.py
> -# -*- coding: utf-8 -*-
Here and further, is this a line we should get rid of or keep?

2022-07-20 11:23 UTC, RubenImhoff commented on pysteps/nowcasts/anvil.py
> +        rainrate_mask = None
Should we add a test line for when rainrate_mask = None?

2022-07-20 11:23 UTC, RubenImhoff commented on pysteps/nowcasts/anvil.py
> +    print(f"R(VIL) window radius:        {r_vil_window_radius}")
Suggestion:
Here and further, @dnerini has been working on replacing all our "R"s in the code to "precip_". Let's do that here, too. So, `precip_vil_window_radius`.

2022-07-20 11:23 UTC, RubenImhoff commented on pysteps/nowcasts/anvil.py
> +        r_vil_a, r_vil_b = None, None
```suggestion
        precip_vil_a, precip_vil_b = None, None
```

2022-07-20 11:23 UTC, RubenImhoff commented on pysteps/nowcasts/anvil.py
>          r_vil_a, r_vil_b = _r_vil_regression(vil[-1, :], rainrate, r_vil_window_radius)
```suggestion
        precip_vil_a, precip_vil_b = _r_vil_regression(vil[-1, :], rainrate, r_vil_window_radius)
```

2022-07-20 11:23 UTC, RubenImhoff commented on pysteps/nowcasts/anvil.py
> +        "r_vil_a": r_vil_a,
```suggestion
        "precip_vil_a": precip_vil_a,
```

2022-07-20 11:23 UTC, RubenImhoff commented on pysteps/nowcasts/anvil.py
> +        "r_vil_b": r_vil_b,
```suggestion
        "precip_vil_b": precip_vil_b,
```

2022-07-20 11:23 UTC, RubenImhoff commented on pysteps/nowcasts/anvil.py
> +        rainrate_f_new = params["r_vil_a"] * vil_f + params["r_vil_b"]
```suggestion
        rainrate_f_new = params["precip_vil_a"] * vil_f + params["precip_vil_b"]
```

And probably at more places in the code.

2022-07-20 11:23 UTC, RubenImhoff commented on pysteps/nowcasts/linda.py
> +    fct = _linda_forecast(
```suggestion
    precip_forecast = _linda_forecast(
```
Or whatever we would like to call it. :)

2022-07-20 11:23 UTC, RubenImhoff commented on pysteps/nowcasts/linda.py
> +    fct = _linda_forecast(
And if changed here, it should also be changed in the rest of the code.

2022-07-20 11:23 UTC, RubenImhoff commented on pysteps/nowcasts/linda.py
>      fct_gen,
```suggestion
    forecast_gen,
```

Perhaps?

2022-07-20 11:23 UTC, RubenImhoff commented on pysteps/nowcasts/linda.py
>      if vel_pert_gen is not None:
```suggestion
    if velocity_pert_gen is not None:
```

Here and in the remainder of the code.

2022-07-20 11:23 UTC, RubenImhoff commented on pysteps/nowcasts/linda.py
> +    precip_f = nowcast_main_loop(
```suggestion
    precip_forecast = nowcast_main_loop(
```

2022-07-20 11:23 UTC, RubenImhoff commented on pysteps/nowcasts/sprog.py
> +    precip_d = []
Again a suggestion that we can, but don't have to, apply:
```suggestion
    precip_decomposed = []
```

2022-07-20 11:23 UTC, RubenImhoff commented on pysteps/nowcasts/sprog.py
> +        precip_ = decomp_method(
```suggestion
        precip_d_ = decomp_method(
```

2022-07-20 11:23 UTC, RubenImhoff commented on pysteps/nowcasts/sprog.py
> +        precip_d.append(precip_)
```suggestion
        precip_decomposed.append(precip_d_)
```

2022-07-20 11:23 UTC, RubenImhoff commented on pysteps/nowcasts/sprog.py
> +    precip_c = nowcast_utils.stack_cascades(
```suggestion
    precip_cascades = nowcast_utils.stack_cascades(
```

2022-07-20 11:23 UTC, RubenImhoff commented on pysteps/nowcasts/sprog.py
> +    precip_f = []
```suggestion
    precip_forecast = []
```

2022-07-20 11:23 UTC, RubenImhoff commented on pysteps/nowcasts/sprog.py
> +    precip_f_recomp = params["recomp_method"](state["precip_d"])
```suggestion
    precip_forecast_recomp = params["recomp_method"](state["precip_d"])
```

2022-07-20 11:23 UTC, RubenImhoff commented on pysteps/nowcasts/sseps.py
> +    psysteps.extrapolation.interface, pysteps.cascade.interface,
```suggestion
    pysteps.extrapolation.interface, pysteps.cascade.interface,
```

2022-07-20 11:23 UTC, RubenImhoff commented on pysteps/nowcasts/sseps.py
> +    f = lambda precip, i: extrapolator_method(
Should we also give `f` a longer name?

2022-07-20 11:23 UTC, RubenImhoff commented on pysteps/nowcasts/sseps.py
> +            P = init_noise(precip, fft_method=fft_method, **noise_kwargs)
```suggestion
            perturb_gen = init_noise(precip, fft_method=fft_method, **noise_kwargs)
```

2022-07-20 11:23 UTC, RubenImhoff commented on pysteps/nowcasts/steps.py
> +        pp = init_noise(precip, fft_method=fft, **noise_kwargs)
```suggestion
        perturb_gen = init_noise(precip, fft_method=fft, **noise_kwargs)
```

2022-07-20 11:23 UTC, RubenImhoff commented on pysteps/nowcasts/steps.py
> +    precip_d = []
If changed in the previous scripts, based on my comments, then change it also here. I have to say that `precip_d` also works for me, so whatever we collectively prefer. 

The same holds for `precip_c` below.

2022-07-20 11:23 UTC, RubenImhoff commented on pysteps/nowcasts/steps.py
> +        for _ in range(n_ens_members):
Is it possible to take this out of a loop?

2022-07-20 11:23 UTC, RubenImhoff commented on pysteps/nowcasts/steps.py
> +            vp = init_vel_noise(velocity, 1.0 / kmperpixel, timestep, **kwargs)
```suggestion
            velocity_perturb = init_vel_noise(velocity, 1.0 / kmperpixel, timestep, **kwargs)
```

2022-07-20 11:23 UTC, RubenImhoff commented on pysteps/nowcasts/steps.py
> +            vps.append(lambda t, vp=vp: generate_vel_noise(vp, t * timestep))
```suggestion
            vps.append(lambda t, vp=velocity_perturb: generate_vel_noise(vp, t * timestep))
```

2022-07-20 11:23 UTC, RubenImhoff commented on pysteps/nowcasts/steps.py
> +    precip_f = nowcast_main_loop(
```suggestion
    precip_forecast = nowcast_main_loop(
```

See also my earlier comments - let's see what we collectively prefer.

2022-07-20 19:48 UTC, dnerini commented
Very nice work @pulkkins and a very much needed cleanup of some of the older modules in pysteps.
I will need to find some time to go through all your changes, in the meantime there are some obvious issues raised by codacy that should be easily fixed: https://app.codacy.com/gh/pySTEPS/pysteps/pullRequest?prid=9807592
can you have a look?

2022-07-23 06:29 UTC, dnerini commented on pysteps/nowcasts/anvil.py
> +    print(f"R(VIL) window radius:        {r_vil_window_radius}")
I suppose in this particular case @pulkkins is referring to a mathematical notation (from the paper) rather than to code?

2022-07-23 06:58 UTC, dnerini commented on pysteps/nowcasts/anvil.py
> +    print(f"R(VIL) window radius:        {r_vil_window_radius}")
Also, changing the name of the argument would constitute a breaking change which we don't want either. Being a bit of a marginal variable, I'm in favour on keeping the original name.

2022-07-23 07:24 UTC, dnerini commented on pysteps/nowcasts/anvil.py
> +        rainrate_mask = None
[e6bacf0](https://github.com/pySTEPS/pysteps/pull/291/commits/e6bacf033de323f2302e247600ce7ac508381c2b)

2022-07-25 06:39 UTC, RubenImhoff commented on pysteps/nowcasts/anvil.py
> +    print(f"R(VIL) window radius:        {r_vil_window_radius}")
Good point, let's keep it this way!

2022-07-25 12:03 UTC, pulkkins commented on pysteps/nowcasts/anvil.py
> +    print(f"R(VIL) window radius:        {r_vil_window_radius}")
> Good point, let's keep it this way!

I agree.

2022-07-25 13:38 UTC, dnerini approved these changes

2022-07-25 13:52 UTC, RubenImhoff approved these changes

2022-07-25 17:06 UTC, dnerini commented
Very good Seppo, I think with this one we can ship v1.7 as soon as you merge it into master

2022-07-26 15:58 UTC, dnerini commented
hey @pulkkins, I just tried to build the documentation, which failed (logs [here](https://readthedocs.org/projects/pysteps/builds/17543008/)) because we renamed many positional arguments of the nowcasting methods... in principle these represent breaking changes (indeed, they broke our documentation ...), which we should apply were carefully to master, you agree?

So what do we do? Should we just revert those changes and change only names for internal variables?

2022-07-26 21:39 UTC, mathause commented
Another possibility is to deprecate the old names in favor of the new ones - this can e.g. be achieved as:

https://github.com/regionmask/regionmask/blob/e5416cc03027c69a0b1a451860c4028d43dadc21/regionmask/core/plot.py#L225-L230

I would also consider making most of the arguments keyword-only e.g. `def f(a, *, b=5)`, this will force the user to write everything out, making it more understandable in the long term. This could be hard-deprecated with:

```python
def func(a, b, c, *args, d=5, e="param"):

    if args:
        raise TypeError("Only three positional arguments allowed")
```

---

For context @leabeusch told me to have a look at pysteps so I did ;-)

2022-07-27 19:25 UTC, dnerini commented
Hello @mathause and welcome to pysteps! Many thanks for your comments, see my answers below.

> Another possibility is to deprecate the old names in favor of the new ones - this can e.g. be achieved as:
> 
> 
> https://github.com/regionmask/regionmask/blob/e5416cc03027c69a0b1a451860c4028d43dadc21/regionmask/core/plot.py#L225-L230

Very good point, yes, we could raise a future deprecation warning for the old argument names. I think I'll give this a try, if you don't mind @pulkkins ?


> I would also consider making most of the arguments keyword-only e.g. `def f(a, *, b=5)`, this will force the user to write everything out, making it more understandable in the long term. This could be hard-deprecated with:
> 
> 
> ```python
> 
> def func(a, b, c, *args, d=5, e="param"):
> 
> 
> 
>     if args:
> 
>         raise TypeError("Only three positional arguments allowed")
> 
> ```
> 

I think we loosely follow this convention in most of our methods (I should check...), but I like the idea of enforcing it. Maybe material for a separate issue?

> 
> For context @leabeusch told me to have a look at pysteps so I did ;-)

Then thanks @leabeusch for sending you this way! 😄

2022-08-05 12:08 UTC, pulkkins commented
I have not yet done extensive refactoring of the nowcasts.sseps module. @dnerini would you like to work on that or should we merge this pull request?

2022-08-05 12:11 UTC, dnerini commented
> I have not yet done extensive refactoring of the nowcasts.sseps module. @dnerini would you like to work on that or should we merge this pull request?

No I think that should not be in scope for this PR. Anyway, it is my intention to deprecate sseps (for sure in v2), since linda provides a better implementation of the localisation mechanism.

2022-08-05 13:07 UTC, merged