[ERAD] Add test cleansing error is raise when input has nans
pySTEPS/pysteps pull request #296
Opened 2022-08-28 12:29 UTC by aperezhortal

This PR adds a test for the cleansing function that checks that an error is raised when input has nans.

2022-08-28 12:35 UTC, aperezhortal reviewed
@dnerini , what do you think? Is it ready?

2022-08-28 12:35 UTC, aperezhortal commented on pysteps/tests/test_utils_cleansing.py
> +    iarr = np.ones((3, 1))
What about using more descriptive variable names? 

`input_array`

2022-08-28 12:35 UTC, aperezhortal commented on pysteps/tests/test_utils_cleansing.py
> +        cleansing.decluster(cor, iarr, scale)
Please, add a new line at the end.

2022-09-16 10:34 UTC, dnerini requested changes
The black test is failing, otherwise this is good to go!

2022-09-22 20:32 UTC, dnerini approved these changes

2022-09-22 20:37 UTC, merged