Add testing for ascending time step raise Value Error
pySTEPS/pysteps pull request #300
Opened 2022-08-28 13:10 UTC by allabakash2

2022-08-30 11:37 UTC, aperezhortal requested changes
Thanks @allabakash2 for submitting the PR! 

I left 2 minor comments about code style that would be great to have before merging this PR.

2022-08-30 11:37 UTC, aperezhortal commented on pysteps/tests/test_extrapolation_semilagrangian.py
> +def test_ascending_time_step():
From the name of the function is not clear what is being tested. 

What about: `test_not_ascending_timesteps_raise_exceptions`

2022-08-30 11:37 UTC, aperezhortal commented on pysteps/tests/test_extrapolation_semilagrangian.py
> +        extrapolate(precip, velocity, not_ascending_timesteps)
End of line missing at line 30. You can fix this and any other format issue by running `black`. After running black, commit the changes.  For this, you don't need the full pysteps development environment on your computer. A simple conda environment with the latest version of black will do the job.

2022-08-30 16:30 UTC, aperezhortal commented on pysteps/tests/test_extrapolation_semilagrangian.py
> +    with pytest.raises(ValueError):
pytest module not imported. 

`import pytest` needs to be added at the top of the file.

2022-09-22 20:19 UTC, dnerini commented
hey @allabakash2 , thanks again for your contribution! Any chance to get this PR done in the coming days? Would be nice to include it in an upcoming release of pysteps ;-)

2024-04-27 11:01 UTC, dnerini commented
closing as duplicate of #302

2024-04-27 11:01 UTC, closed without merging