fixed future warning
pySTEPS/pysteps pull request #301
Opened 2022-08-28 13:13 UTC by feldmann-m

fixed future warning from scikit-image

2022-08-28 13:18 UTC, pierrejavelle commented
The pull request is not describing the issue it is trying to solve.

2022-08-28 13:27 UTC, feldmann-m commented
Scikit image raises a future warning when using the keyword "selem" in the h_maxima function. This has been replaced with "footprint", which is the new name for this  keyword.

2022-09-15 10:36 UTC, dnerini requested changes
Very nice, thanks a lot @feldmann-m !

One small detail: the new argument name won't work for scikit-image < 0.19, therefore I suggest that you specify this minimum version in the documentation:

in the file `pysteps/doc/source/user_guide/install_pysteps.rst`
please specify `scikit-image >= 0.19`

2022-09-25 20:40 UTC, dnerini approved these changes

2022-09-25 20:42 UTC, merged