Added citation in documentation of tstorm and tdating
pySTEPS/pysteps pull request #304
Opened 2022-08-28 13:22 UTC by feldmann-m

This adds the publication with the documentation to the files tstorm.py and tdating.py . The code is not changed.

2022-08-30 22:22 UTC, aperezhortal commented on pysteps/tracking/tdating.py
> +Full ducomentation is published in :cite:`Feldmann2021`.
```suggestion
Full documentation is published in :cite:`Feldmann2021`.
```

2022-08-30 22:23 UTC, aperezhortal commented on pysteps/feature/tstorm.py
> +Full ducomentation is published in :cite:`Feldmann2021`.
```suggestion
Full documentation is published in :cite:`Feldmann2021`.
```

2022-08-30 22:24 UTC, aperezhortal requested changes
Thanks for submitting the PR! I left two small suggestions in the review.

2022-09-16 08:27 UTC, dnerini approved these changes

2022-09-16 08:28 UTC, merged