Improve forecast animations
pySTEPS/pysteps pull request #63
Opened 2019-03-21 14:47 UTC by loforest

- Improve the visualization of animations, e.g.  text for titles, lead times, members.
- Add observed probability (binary) plots
- Change order of animation,  looping first over all lead times and then changing prob. threshold

2019-03-21 18:17 UTC, dnerini requested changes
I've tested the pull request with the my_first_nowcast_with_pysteps.py and run_ensemble_nowcast.py examples.

The changes work very well for the run_ensemble_nowcast.py, also when probabilities or the ensemble mean are plotted.

However, I get an error when I try to run the simpler my_first_nowcast_with_pysteps.py:

>Traceback (most recent call last):
  File "my_first_nowcast_with_pysteps.py", line 58, in <module>
    stp.plt.animate(R, R_fct=R_fct, UV=UV, nloops=5) 
  File "/home/ned/anaconda3/envs/pysteps/lib/python3.6/site-packages/pysteps-0.2-py3.6-linux-x86_64.egg/pysteps/visualization/animations.py", line 183, in animate
    plt.text(0.99, 0.99, leadtime, transform=ax.transAxes, ha="right", va="top")
UnboundLocalError: local variable 'leadtime' referenced before assignment

2019-03-22 05:46 UTC, loforest commented
Thanks for testing the new animation routine. I understood the issue and
will fix it.

Il Gio 21 Mar 2019, 19:17 Daniele Nerini <notifications@github.com> ha
scritto:

> *@dnerini* requested changes on this pull request.
>
> I've tested the pull request with the my_first_nowcast_with_pysteps.py and
> run_ensemble_nowcast.py examples.
>
> The changes work very well for the run_ensemble_nowcast.py, also when
> probabilities or the ensemble mean are plotted.
>
> However, I get an error when I try to run the simpler
> my_first_nowcast_with_pysteps.py:
>
> Traceback (most recent call last):
> File "my_first_nowcast_with_pysteps.py", line 58, in
> stp.plt.animate(R, R_fct=R_fct, UV=UV, nloops=5)
> File
> "/home/ned/anaconda3/envs/pysteps/lib/python3.6/site-packages/pysteps-0.2-py3.6-linux-x86_64.egg/pysteps/visualization/animations.py",
> line 183, in animate
> plt.text(0.99, 0.99, leadtime, transform=ax.transAxes, ha="right",
> va="top")
> UnboundLocalError: local variable 'leadtime' referenced before assignment
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pySTEPS/pysteps/pull/63#pullrequestreview-217413754>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AmJXBTqvHcsR97Kov4ren-o-Hjh61IeIks5vY8ylgaJpZM4cBm6->
> .
>

2019-03-24 16:38 UTC, dnerini approved these changes

2019-04-01 12:47 UTC, dnerini approved these changes
This looks good and seems to work very nicely on my examples.

2019-04-01 13:19 UTC, merged